export const PROPERTY_TYPES = [
  { value: "apartment", label: "Apartment" },
  { value: "house", label: "House" },
  { value: "studio", label: "Studio" },
  { value: "villa", label: "Villa" },
  { value: "room", label: "Room" },
  { value: "townhouse", label: "Townhouse" },
  { value: "condo", label: "Condo" },
];

export const AMENITIES = [
  "Swimming Pool",
  "Gym",
  "Parking",
  "Security",
  "Elevator",
  "Balcony",
  "Garden",
  "Rooftop",
  "Concierge",
  "Laundry",
  "Storage",
  "Pet-Friendly",
];

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "price_asc", label: "Lowest Price" },
  { value: "price_desc", label: "Highest Price" },
  { value: "most_popular", label: "Most Popular" },
];

export const BEDROOM_OPTIONS = [
  { value: "0", label: "Studio" },
  { value: "1", label: "1 Bedroom" },
  { value: "2", label: "2 Bedrooms" },
  { value: "3", label: "3 Bedrooms" },
  { value: "4", label: "4+ Bedrooms" },
];

export const MOCK_PROPERTIES = [
  {
    _id: "1",
    title: "Luxurious Modern Apartment in Downtown",
    description:
      "Experience urban living at its finest in this stunning modern apartment. Floor-to-ceiling windows offer breathtaking city views, while premium finishes throughout create an atmosphere of sophisticated luxury. The open-plan living area seamlessly connects to a gourmet kitchen with top-of-the-line appliances.",
    type: "apartment",
    price: 2800,
    priceType: "monthly",
    location: {
      address: "123 Downtown Ave",
      city: "New York",
      state: "NY",
      country: "USA",
      neighborhood: "Manhattan",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
    ],
    amenities: ["Swimming Pool", "Gym", "Parking", "Security", "Elevator"],
    features: {
      furnished: true,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: true,
      airConditioning: true,
      gym: true,
      pool: true,
      laundry: true,
    },
    landlord: {
      _id: "l1",
      name: "Michael Johnson",
      email: "michael@example.com",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0101",
      bio: "Professional property manager with 10+ years experience",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 342,
    inquiries: 28,
    availableFrom: "2025-02-01",
    rating: 4.8,
    reviewCount: 23,
    createdAt: "2025-01-15",
    updatedAt: "2025-01-15",
  },
  {
    _id: "2",
    title: "Charming Studio in Arts District",
    description:
      "Beautifully renovated studio apartment in the heart of the vibrant Arts District. Exposed brick walls, polished concrete floors, and large industrial windows give this space a unique character. Perfect for young professionals seeking a creative living environment.",
    type: "studio",
    price: 1400,
    priceType: "monthly",
    location: {
      address: "456 Arts Blvd",
      city: "Los Angeles",
      state: "CA",
      country: "USA",
      neighborhood: "Arts District",
      coordinates: { lat: 34.0522, lng: -118.2437 },
    },
    bedrooms: 0,
    bathrooms: 1,
    area: 550,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
    ],
    amenities: ["Laundry", "Security"],
    features: {
      furnished: true,
      parking: false,
      petFriendly: true,
      security: true,
      water: true,
      electricity: true,
      internet: true,
      airConditioning: false,
      gym: false,
      pool: false,
      laundry: true,
    },
    landlord: {
      _id: "l2",
      name: "Sarah Williams",
      email: "sarah@example.com",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0202",
      bio: "Independent landlord with boutique properties",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 215,
    inquiries: 18,
    availableFrom: "2025-02-15",
    rating: 4.5,
    reviewCount: 15,
    createdAt: "2025-01-10",
    updatedAt: "2025-01-10",
  },
  {
    _id: "3",
    title: "Spacious Family Home with Garden",
    description:
      "This beautifully appointed family home sits in a quiet, tree-lined street in one of the most sought-after neighborhoods. The property features a large open-plan kitchen and living area that opens to a private garden, perfect for entertaining.",
    type: "house",
    price: 4500,
    priceType: "monthly",
    location: {
      address: "789 Oak Street",
      city: "San Francisco",
      state: "CA",
      country: "USA",
      neighborhood: "Pacific Heights",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
    ],
    amenities: ["Garden", "Parking", "Security"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: true,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: true,
      gym: false,
      pool: false,
      laundry: true,
    },
    landlord: {
      _id: "l3",
      name: "David Chen",
      email: "david@example.com",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0303",
      bio: "Real estate investor specializing in family homes",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 487,
    inquiries: 42,
    availableFrom: "2025-03-01",
    rating: 4.9,
    reviewCount: 31,
    createdAt: "2025-01-05",
    updatedAt: "2025-01-05",
  },
  {
    _id: "4",
    title: "Elegant Villa with Pool",
    description:
      "Indulge in the ultimate luxury living experience with this magnificent villa. Set within a prestigious gated community, this masterpiece of contemporary architecture offers unparalleled comfort and style with a private pool and lush tropical garden.",
    type: "villa",
    price: 8500,
    priceType: "monthly",
    location: {
      address: "321 Palm Drive",
      city: "Miami",
      state: "FL",
      country: "USA",
      neighborhood: "Coral Gables",
      coordinates: { lat: 25.7617, lng: -80.1918 },
    },
    bedrooms: 5,
    bathrooms: 4,
    area: 5200,
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    ],
    amenities: ["Swimming Pool", "Gym", "Parking", "Security", "Garden"],
    features: {
      furnished: true,
      parking: true,
      petFriendly: true,
      security: true,
      water: true,
      electricity: true,
      internet: true,
      airConditioning: true,
      gym: true,
      pool: true,
      laundry: true,
    },
    landlord: {
      _id: "l4",
      name: "Amanda Roberts",
      email: "amanda@example.com",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0404",
      bio: "Luxury property specialist with premium portfolio",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 623,
    inquiries: 55,
    availableFrom: "2025-02-01",
    rating: 5.0,
    reviewCount: 12,
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
  },
  {
    _id: "5",
    title: "Modern Condo Near Tech Hub",
    description:
      "Perfectly positioned for Silicon Valley professionals, this sleek modern condo offers effortless access to major tech companies. The building features state-of-the-art amenities including a rooftop terrace with panoramic views.",
    type: "condo",
    price: 3200,
    priceType: "monthly",
    location: {
      address: "555 Innovation Way",
      city: "Seattle",
      state: "WA",
      country: "USA",
      neighborhood: "South Lake Union",
      coordinates: { lat: 47.6062, lng: -122.3321 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800",
    ],
    amenities: ["Rooftop", "Gym", "Concierge", "Elevator"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: true,
      airConditioning: true,
      gym: true,
      pool: false,
      laundry: true,
    },
    landlord: {
      _id: "l5",
      name: "Robert Kim",
      email: "robert@example.com",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0505",
      bio: "Urban property developer",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: false,
    views: 298,
    inquiries: 22,
    availableFrom: "2025-02-20",
    rating: 4.6,
    reviewCount: 18,
    createdAt: "2025-01-12",
    updatedAt: "2025-01-12",
  },
  {
    _id: "6",
    title: "Cozy Townhouse with Patio",
    description:
      "Nestled in a quiet residential area, this charming townhouse offers the perfect balance of privacy and community living. The private patio is ideal for morning coffee or evening relaxation, while the modern interior provides all the comforts of contemporary life.",
    type: "townhouse",
    price: 2200,
    priceType: "monthly",
    location: {
      address: "88 Maple Court",
      city: "Austin",
      state: "TX",
      country: "USA",
      neighborhood: "East Austin",
      coordinates: { lat: 30.2672, lng: -97.7431 },
    },
    bedrooms: 3,
    bathrooms: 2,
    area: 1800,
    images: [
      "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800",
    ],
    amenities: ["Parking", "Balcony", "Storage"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: true,
      security: false,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: true,
      gym: false,
      pool: false,
      laundry: true,
    },
    landlord: {
      _id: "l6",
      name: "Jennifer Lopez",
      email: "jennifer@example.com",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
      role: "landlord",
      verified: true,
      phone: "+1 555-0606",
      bio: "Friendly landlord with well-maintained properties",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: false,
    views: 176,
    inquiries: 14,
    availableFrom: "2025-03-15",
    rating: 4.4,
    reviewCount: 9,
    createdAt: "2025-01-18",
    updatedAt: "2025-01-18",
  },
];
