export const PROPERTY_TYPES = [
  { value: "all", label: "All" },
  { value: "single-room", label: "Single Room" },
  { value: "apartment", label: "Apartment" },
  { value: "self-contain", label: "Self Contain" },
  { value: "chamber-hall", label: "Chamber & Hall" },
  { value: "house", label: "House" },
  { value: "office", label: "Office Space" },
];

export const AMENITIES = [
  "Wi-Fi",
  "Parking",
  "Air Condition",
  "Water",
  "Furnished",
  "Security",
  "Generator",
  "Kitchen",
  "Balcony",
  "CCTV",
];

export const SORT_OPTIONS = [
  { value: "newest", label: "Newest First" },
  { value: "price_asc", label: "Lowest Price" },
  { value: "price_desc", label: "Highest Price" },
  { value: "most_popular", label: "Most Popular" },
];

export const BEDROOM_OPTIONS = [
  { value: "0", label: "Room Only" },
  { value: "1", label: "1 Bedroom" },
  { value: "2", label: "2 Bedrooms" },
  { value: "3", label: "3 Bedrooms" },
  { value: "4", label: "4+ Bedrooms" },
];

export const GHANA_LOCATIONS = [
  "East Legon, Accra",
  "West Legon, Accra",
  "Madina, Accra",
  "Tema Community 25",
  "Adenta, Accra",
  "Achimota, Accra",
  "Spintex, Accra",
  "Kasoa, Central",
  "Kumasi, Ashanti",
  "Takoradi, Western",
];

export const MOCK_PROPERTIES = [
  {
    _id: "1",
    title: "2 Bedroom Apartment",
    description:
      "Spacious 2-bedroom apartment in a serene environment. All rooms ensuite with pop ceiling and modern kitchen. Water and electricity included. Close to shops, schools and transport.",
    type: "apartment",
    price: 3000,
    priceType: "monthly",
    location: {
      address: "Airport Residential Area",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "West Legon",
      coordinates: { lat: 5.6037, lng: -0.187 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
    ],
    amenities: ["Parking", "Security", "Water", "Kitchen", "Air Condition"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: true,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l1",
      name: "Kofi Mensah",
      email: "kofi@example.com",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0001",
      bio: "Property manager in Greater Accra with 8+ years experience",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 342,
    inquiries: 28,
    availableFrom: "2025-02-01",
    rating: 4.8,
    reviewCount: 23,
    createdAt: "2025-01-15",
    updatedAt: "2025-01-15",
  },
  {
    _id: "2",
    title: "2 Bedroom Apartment",
    description:
      "Modern 2-bedroom apartment in a prime location. Fully tiled with quality fittings. Generator backup, borehole water, and 24-hour security.",
    type: "apartment",
    price: 2500,
    priceType: "monthly",
    location: {
      address: "Lakeside Estate",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "East Legon",
      coordinates: { lat: 5.636, lng: -0.153 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 100,
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
    ],
    amenities: ["Security", "Water", "Parking", "Generator"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: false,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l2",
      name: "Akosua Asante",
      email: "akosua@example.com",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0002",
      bio: "Real estate investor with residential properties across Accra",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 215,
    inquiries: 18,
    availableFrom: "2025-02-15",
    rating: 4.5,
    reviewCount: 15,
    createdAt: "2025-01-10",
    updatedAt: "2025-01-10",
  },
  {
    _id: "3",
    title: "Single Room (Self Contain)",
    description:
      "Clean and well-maintained single room self-contain. Includes washroom and kitchen. Water and electricity metered. Suitable for single occupants or couples.",
    type: "single-room",
    price: 700,
    priceType: "monthly",
    location: {
      address: "New Legon Road",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "Madina",
      coordinates: { lat: 5.679, lng: -0.171 },
    },
    bedrooms: 1,
    bathrooms: 1,
    area: 30,
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
      "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800",
    ],
    amenities: ["Water", "Security", "Kitchen"],
    features: {
      furnished: false,
      parking: false,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: false,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l3",
      name: "Yaw Darko",
      email: "yaw@example.com",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0003",
      bio: "Landlord with affordable housing options in Madina",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 487,
    inquiries: 42,
    availableFrom: "2025-03-01",
    rating: 4.2,
    reviewCount: 11,
    createdAt: "2025-01-05",
    updatedAt: "2025-01-05",
  },
  {
    _id: "4",
    title: "Executive Studio",
    description:
      "Beautifully furnished executive studio in a prestigious area. All inclusive with high-speed Wi-Fi, air conditioning, and 24-hour security. Ideal for professionals.",
    type: "self-contain",
    price: 1800,
    priceType: "monthly",
    location: {
      address: "Airport Residential Area",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "Airport Residential",
      coordinates: { lat: 5.598, lng: -0.172 },
    },
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    ],
    amenities: ["Wi-Fi", "Air Condition", "Security", "Furnished", "Generator"],
    features: {
      furnished: true,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: true,
      airConditioning: true,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l4",
      name: "Abena Osei",
      email: "abena@example.com",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0004",
      bio: "Executive property specialist in Airport Residential",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: true,
    views: 623,
    inquiries: 55,
    availableFrom: "2025-02-01",
    rating: 4.9,
    reviewCount: 32,
    createdAt: "2025-01-01",
    updatedAt: "2025-01-01",
  },
  {
    _id: "5",
    title: "2 Bedroom Apartment",
    description:
      "Brand new 2-bedroom apartment in a gated community. Spacious living area, fitted kitchen, and covered parking. Close to Tema motorway.",
    type: "apartment",
    price: 2200,
    priceType: "monthly",
    location: {
      address: "Community 25",
      city: "Tema",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "Tema Community 25",
      coordinates: { lat: 5.625, lng: -0.003 },
    },
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800",
    ],
    amenities: ["Parking", "Security", "Water", "Generator"],
    features: {
      furnished: false,
      parking: true,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: false,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l5",
      name: "Kwame Boateng",
      email: "kwame@example.com",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0005",
      bio: "Property developer with residential complexes in Tema",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: false,
    views: 298,
    inquiries: 22,
    availableFrom: "2025-02-20",
    rating: 4.3,
    reviewCount: 8,
    createdAt: "2025-01-12",
    updatedAt: "2025-01-12",
  },
  {
    _id: "6",
    title: "Chamber & Hall Self Contain",
    description:
      "Well-kept chamber and hall self-contain in a quiet neighborhood. Includes indoor kitchen and bathroom. Water and electricity available. Safe environment.",
    type: "chamber-hall",
    price: 900,
    priceType: "monthly",
    location: {
      address: "Achimota Road",
      city: "Accra",
      state: "Greater Accra",
      country: "Ghana",
      neighborhood: "Achimota",
      coordinates: { lat: 5.614, lng: -0.231 },
    },
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    images: [
      "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800",
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800",
    ],
    amenities: ["Water", "Security", "Kitchen"],
    features: {
      furnished: false,
      parking: false,
      petFriendly: false,
      security: true,
      water: true,
      electricity: true,
      internet: false,
      airConditioning: false,
      gym: false,
      pool: false,
      laundry: false,
    },
    landlord: {
      _id: "l6",
      name: "Ama Agyei",
      email: "ama@example.com",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150",
      role: "landlord",
      verified: true,
      phone: "+233 24 000 0006",
      bio: "Friendly landlord with affordable properties in Achimota",
      favorites: [],
      createdAt: "2024-01-01",
    },
    status: "available",
    verified: true,
    featured: false,
    views: 176,
    inquiries: 14,
    availableFrom: "2025-03-15",
    rating: 4.1,
    reviewCount: 7,
    createdAt: "2025-01-18",
    updatedAt: "2025-01-18",
  },
];
